spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homey?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: stardotsnow13
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181

